services:
  eureka-service:
    image: eureka-service   # 이미지 이름
    build:
      context: ./BE/eureka-service # Dockerfile이 있는 디렉토리
      dockerfile: Dockerfile.local # Dockerfile 이름
    container_name: eureka-service # 컨테이너 이름
    ports:
      - "45001:45001" # 포트 매핑
    environment:
      - SPRING_PROFILES_ACTIVE=docker  # Docker 실행 시 docker 프로파일 사용
    networks:
      - app_network # 네트워크 연결

  gw-service:
    image: gw-service # 이미지 이름
    build:
      context: BE/gw-service # Dockerfile이 있는 디렉토리
      dockerfile: Dockerfile.local # Dockerfile 이름
    container_name: gw-service # 컨테이너 이름
    ports:
      - "45000:45000" # 포트 매핑
      - "45100:45100" # 디버그 포트 매핑
    depends_on:
      - eureka-service # 의존성 설정
    environment:
      - SPRING_PROFILES_ACTIVE=docker # Docker 실행 시 docker 프로파일 사용
    networks:
      - app_network # 네트워크 연결

volumes:
  redis_data:

networks:
  app_network:
    name: app_network
    driver: bridge
