spring:
  application:
    name: elh-service
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    view-names: /th/*
    check-template-location: true
  h2:
    console:
      enabled: false

server:
  port: 45003

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}