spring:
  application:
    name: gw-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]' :
            allowedOrigins:
              - "http://localhost:45000"
            allowedMethods: "GET,POST,PUT,DELETE"
            allowedHeaders: "Authorization"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id : crm-service
          uri: lb://crm-service
          predicates:
            - Path=/crm/**, /css/**, /images/**
        - id: elh-service
          uri: lb://elh-service
          predicates:
            - Path=/elh/**


logging:
  level:
    org.springframework.web: DEBUG           # Spring Web의 HTTP 요청과 응답 로그
    org.springframework.cloud.gateway: DEBUG # Spring Cloud Gateway의 요청과 응답 로그

server:
  port: 45000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}