spring:
  application:
    name: gw-service
  cloud:
    gateway:
      paths-to-exclude:
        - ${ROOT_PATH}/index
        - ${ROOT_PATH}/lgin
        - ${ROOT_PATH}/js
        - ${ROOT_PATH}/css
        - ${ROOT_PATH}/images
        - ${ROOT_PATH}/libs
        - ${ROOT_PATH}/auth
      default-filters:
        - name : GlobalFilter
          args :
            baseMessage : Spring Cloud Gateway Global Filter
            preLogger  : true
            postLogger : true
      globalcors:
        cors-configurations:
          '[/**]' :
            allowedOrigins:
              - "http://localhost:45000"
            allowedMethods: "GET,POST,PUT,DELETE"
            allowedHeaders: "Authorization"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id : crm-service
          uri: lb://crm-service
          predicates:
            - Path=${ROOT_PATH}/*, ${ROOT_PATH}/**, ${ROOT_PATH}/**

        - id: elh-service
          uri: lb://elh-service
          predicates:
            - Path=/elh/**



logging:
  level:
    org.springframework.web: DEBUG           # Spring Web의 HTTP 요청과 응답 로그
    org.springframework.cloud.gateway: DEBUG # Spring Cloud Gateway의 요청과 응답 로그
    org.gateway : DEBUG

server:
  port: 45000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}

ncrm:
  redirect: ${REDIRECT_PATH}${ROOT_PATH}/auth