spring:
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    view-names: /th/*
    check-template-location: true

  web:
    resources:
      static-locations: file:/app/share_resources/


server:
  port: 45002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}


logging:
  level:
    org:
      thymeleaf: debug
